name: ci

on:
  push:
    branches:
      - "**"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Debug GCC 13 C++17
        run: ./build.sh docker=gcc13 debug clean uban=on asan=off test
      - name: Build Release GCC 13 C++17
        run: ./build.sh docker=gcc13 release clean test doc

      - name: Build Debug Clang 16 C++17
        run: ./build.sh docker=clang16 debug clean uban=on asan=on test
      - name: Build Release Clang 16 C++17
        run: ./build.sh docker=clang16 release clean test doc

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Conan 1.x
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.61.0

      - name: Build Debug AppleClang C++17
        run: ./build.sh debug clean uban=on asan=on test
      - name: Build Release AppleClang C++17
        run: ./build.sh release clean test
